inex/IXP-Manager

tools/runtime/l2database/update-l2database.pl
tools/sql/views.sql

MACs which are behind a logical interface are imported by saving the virtual interface name in the DB and matching on those. This fixes the issues discussed in https://github.com/inex/IXP-Manager/issues/126 for me and gives me sFlow stats for LAGs.

importing LAG MAC addresses 

---

.gitignore

In a previous commit (6aad7a29fe170000af8cd1bd6f0d944b9eb84029) tools/perl-lib/IXPManager/ixpmanager.conf was moved to tools/perl-lib/IXPManager/ixpmanager.conf.dist, so like for the other .dist files it is useful to gitignore the non-dot-dist version.

gitignore perl-lib ixpmanager.conf,there is .dist

---

tools/runtime/route-servers/compare-route-server-prefixes.pl

These are two trivial changes I did while tweaking the RS prefix analysis tool for our setup. I realise the intention is to migrate all of this to core PHP code anyway, but in the meantime these are small/non-invasive and can't hurt for the perl version.
Also, I just sent to the mailing-list (*not* part of a pull-request) the git-diff of other bigger site-specific tweaks I had to make for our configs, as it obviously isn't intended to be applied upstream, but purely as a helpful reference. It applies on top of these commits.

Prefix analysis tool tweaks

---

application/views/admin/index.phtml

Add total connected capacity sums to Customer Ports by Infrastructure section.
You might find the 'divide by 1000 and convert to G' methodology awful. I don't know. ;)

Add Connected Capacity totals to admin interface

---

application/views/customer/overview-tabs/details.phtml

When getBillingFrequency or getInvoiceMethod for a client is the
empty string (example database includes some clients with those
two db fields empty), the application/views/customer/
overview-tabs/details.phtml will throw an error complaining about
an undefined index. Indeed, the CompanyBillingDetail entity includes two
static arrays named $INVOICE_METHODS and $BILLING_FREQUENCIES.
Neither has the '' empty string key, hence the undefined index exception.
To fix, we check for the empty string with both getBillingFrequency
and getInvoiceMethod before trying to use their value as the array
index.

Fix exception when BillingFrequency or InvoiceMethod is empty

---

app/Services/Grapher/Graph.php
app/Services/Grapher/Renderer/Extensions/Grapher.php
app/Utils/Grapher/Mrtg.php
database/Entities/SwitchPort.php

In addition to the rest of the existing categories of packet and
traffic graphs, broadcast packet graphs are added.

Add broadcast packet graphs for MRTG

---

tools/installers/ubuntu-lts-1604-ixp-manager-v4.sh

Hello,
I noticed an issue with the vagrant startup script.
During the "Running composer to install PHP dependencies (please be patient)..." step it broke.
I found the following error within the log:
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.
Problem 1
- Installation request for s1lentium/iptools v1.1.0 -> satisfiable by s1lentium/iptools[v1.1.0].
- s1lentium/iptools v1.1.0 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
...
```
A `sudo apt install php7.0-bcmath` fixed it.
Perhaps also the Docs » Installation » Manual Installation page needs to be updated.
Moreover: are the `Vagrantfile` and …

fix vagrant setup script: 'php7.0-bcmath' missing

---

.travis.yml

[NF] Adds two more recent PHP versions to Travis CI

Add PHP 7.1 and 7.2 to Travis test matrix

---

resources/views/search/do.foil.php
routes/web.php

p2p link from search needs updating

[BF] - p2p link from search needs updating - fixes inex/IXP-Manager#424

---

resources/views/customer/delete.foil.php

Cannot delete clients
The CSRF token was missing in the delete form.

[BF] - Cannot delete clients - fixes inex/IXP-Manager#433

---

app/Listeners/Customer/Note/EmailOnChange.php

Customer note notification : Dont send notification email if customer has no email
- check email is not null + check email valid

Issue 435 - Customer note notification : Dont send notification email if customer has no email

---

app/Http/Controllers/Customer/CustomerController.php

Cannot save Left date in 4.8.0 interface.

[BF] - Cannot save Left date in 4.8.0 interface.

---

app/Http/Controllers/Customer/CustomerController.php
app/Http/Requests/Customer/BillingInformation.php

Customer with no country defaults to "Afghanistan"
I dont know if it was the best way to fix that bug, the countries are generated with the [Laravel Countries](https://github.com/webpatser/laravel-countries) with a dedicated table in the DB. 
The other way was to add a new entry in the table with empty fields.

[BF] - Customer with no country defaults to "Afghanistan"

---

resources/views/api-key/list-postamble.foil.php

[BF] - Bad link for Test API Key - fixes inex/IXP-Manager#451

---

resources/views/patch-panel-port/view.foil.php

When viewing a patch panel port, make the customer name a hype

When viewing a patch panel port, make the customer name a hyperlink

---

app/Http/Controllers/StatisticsController.php

There is a bug in the logic of the loop iterating over $targets in StatisticsController::members(), see line 320 of app/Http/Controllers/StatisticsController.php. In the case where $infra and $vlan are false, the loop will try to check whether $t->isGraphable() (line 328). But if it is not, the loop will *not* stop, and the graph $g will retain the value from the previous loop. Which means that the previous diagram $g will be pushed into $graphs and shown once more. The final effect is that, for each non-graphable member, the previous member's graph gets shown twice. This is obviously a bug. To correct, we simply add an 'else { continue; }' to go directly to the next loop.
*PR template - remove this line and edit below* …

Fix subtle bug in StatisticsController::members()

---

resources/views/interfaces/virtual/add/vi-details.foil.php
resources/views/interfaces/virtual/js/interface.foil.php
tests/Browser/VirtualInterfaceControllerTest.php

Change redirection after deleting a (virtual) interface + dusk test modification

Change redirection after deleting a (virtual) interface

---

database/Repositories/PatchPanelPort.php

Prewired duplex ports
While prewiring ports, if set to duplex ports, the partner port is still able to be allocated to other ports as a partner port.

[IM] - Prewired duplex ports - fixes inex/IXP-Manager#449

---

resources/views/customer/overview-tabs/ports/port.foil.php

Netmask doesn't show under Ports

[BF] - Netmask doesn't show under Ports - fixes inex/IXP-Manager#522

---

resources/views/layer2-address/vlan-interface.foil.php

issue when the create date of a Layer 2 Address is null
- [x ] API calls (particular for add/edit/delete/toggle) are not implemented with GET and use CSRF tokens to avoid CSRF attacks

[BF] - issue when the create date of a Layer 2 Address is null

---

resources/scss/tailwind.scss
resources/views/customer/overview-tabs/notes.foil.php

[BF] - fix issue left hand side menu

[BF] - fix issue left hand side menu

---

resources/views/services/lg/bgp-summary.foil.php

RS Looking Glass sort order - fixes inex/IXP-Manager#544

---

resources/views/patch-panel-port/action-dd.foil.php
resources/views/patch-panel-port/view.foil.php

hide download/view LOA for patch panel port without customer assigned

[BF] - hide download/view LOA for patch panel port without customer assigned

---

resources/views/layer2-address/vlan-interface.foil.php

Issue configured mac address management display 1 after the IP address

Issue configured mac address management display 1 after the IP address

---

resources/views/user/edit.foil.php
tests/Browser/UserControllerTest.php

Error500 on User Mgmt - fixes inex/IXP-Manager#579

---

app/Http/Controllers/LoginHistoryController.php
resources/views/customer/overview-tabs/users.foil.php

Wrong login history displayed for user

[BF] - Wrong login history displayed for user - fixes inex/IXP-Manager#594

---

app/Http/Controllers/Switches/SwitchController.php

Remove one comma that was breaking switch controller

[BF] - remove comma that was making php error

---

app/Http/Controllers/SecurityPasswordController.php
app/Support/Google2FAAuthenticator.php

Fix the issue asking twice the 2fa code

[BF] - fix issue asking twice the 2fa code

---

resources/views/switches/configuration.foil.php

switch configuration generate error 500

[BF] - switch configuration generate error 500

---

database/Repositories/User.php

Fix the 404 error when trying to view a login history via last logins entry menu

[BF] - fix issue : last logins -> login history ->  view -> generate 404

---

app/Http/Middleware/Google2FA.php
app/Utils/Foil/Extensions/IXP.php
database/Entities/User.php
database/Proxies/__CG__EntitiesUser.php
resources/views/layouts/ixpv4.foil.php
resources/views/user/2fa/configure/enable.foil.php

- Fix the 2FA issue with the hidden/show lateral menu 
- Fix the middleware not checking if 2fa enabled or not

[BF] - Fix issues with 2FA

---

resources/views/auth/login.foil.php
resources/views/layouts/menus/associate.foil.php
resources/views/layouts/menus/custadmin.foil.php
resources/views/layouts/menus/custuser.foil.php
resources/views/layouts/menus/superuser.foil.php
tests/Browser/UserRememberTokenControllerTest.php

Remember me session management

[DUSK] - remember me session management

---

resources/views/customer/overview.foil.php

inex/IXP-Manager#616  - Logo alignment in public member details page

[BF] - customer logo alignement - fixes inex/IXP-Manager#616

---

app/Http/Controllers/Switches/SwitchPortController.php

[BF] - Bug in Switches List Live Port State section - fixes inex/IXP-Manager#621

---

database/Entities/PatchPanelPort.php

Patch Panels Customer View: State 'Reserved' appears white text on white background - fixes inex/IXP-Manager#637

[BF] - Patch Panels Customer View: State 'Reserved' appears white text on white background 

---

data/travis-ci/travis_ci_test_db.sql
tests/DocstoreCustomer/Controllers/DirectoryControllerTest.php
tests/DocstoreCustomer/Controllers/FileControllerTest.php

Fix test docstore

---

resources/views/customer/overview-tabs/ports/port.foil.php

Resolves issue #643 - allows a customer to add an initial MAC address by removing the check for >0 MACs.

Allow a customer to add an inital MAC address. Resolves #643

---

resources/views/customer/overview-tabs/ports/port.foil.php

[NF] New feature summary - closes #636 
Display MD5 password for RS/RC peering sessions on customer backend

[NF] Implements #636 - Display MD5 password for RS/RC peering sessions on customer backend

---

app/Listeners/Auth/LoginFailed.php
app/Providers/EventServiceProvider.php

[NF] Logging for failed auth events - implements inex/IXP-Manager #642 
This PR dedicated to our friends at @swissix implements logging for failed auth events into `laravel.log` like in prior versions of IXP manager. We probably should create a proper migration and persist failed logon events into the database with a dedicated backend view in the future, but for the moment this should be enough. Honestly I even like this method because this way we can use fail2ban on laravel.log to automatically block offending IPs.

[NF] Implements #642 - Logging for failed auth events

---

tools/runtime/dns-arpa/update-dns-from-ixp-manager.sh

The sample script to update reverse zones does not check for correctness. Although peoples DNS setup will be very diverse, this script could give a hint how to use named-checkzone for that.
When run with an invalid zonefile the sample script should give some indication of that.
If you favour a specific implementation i'm happy to adapt the patch.

[NF] update-dns-from-ixp-manager.sh sample script could warn on zonefile errors

---

resources/views/patch-panel-port/verify-loa.foil.php

ppp->getPatchPanel()->getCabinet()->getCololocation()

[BF] Rack field in patch panel LoA verification page is blank

---

app/Http/Controllers/Auth/SwitchUserController.php
app/Listeners/Auth/LoginSuccessful.php

admin 'log on as this user' updates last login date 

[BF] - admin 'log on as this user' updates last login date 

---

tools/runtime/route-servers/crontab

[BF] Add missing "-" in example - fixes IXP-Manager

Add missing "-" in example

---

resources/views/peering-matrix/index.foil.php

[BF] Summary of fix - fixes IXP-Manager
Fixed by not prefixing config items with "options.".
- [?] ensured all relevant template output is escaped to avoid XSS attached with `<?= $t->ee( $data ) ?>` or equivalent.

Fix: Peering Matrix view displays empty orgname in help text

---

resources/views/services/lg/router-tab.foil.php

[BF] Guard against null in router->last-updated - fixes IXP-Manager
The /lg page renders the error "500 Server Error :: Call to a member function format() on null" if router->last-updated is null.
Fixed by rendering "(unknown)" if null.

Fix: Guard against null in router->last-updated on /lg page

---

database/Entities/Switcher.php

[NF] Cisco / Huawei use ifType l2vlan for subinterfaces

Cisco / Huawei use ifType l2vlan for subinterfaces

---

app/Models/PatchPanelPort.php

**Longer description**
Putting back my tweak to make the port / position less confusing for the colocation facilities in the LoA.
The colos are not understanding what we mean on the LoA by:  `"Port: 17/18 (9)"`
Changed output like  `"17/18 (9)"` to something more descriptive, so it reads:
`Port: 2 (Fibre Pair, Positions 3/4) (duplex port)`
So with any luck the colo will patch it to the correct port on the panel (we can but try!)
This is still not perfect because different colos expect different things.
(Some require the number to refer to a pair, others want the individual fibre positions in a pair. Sending both can cause confusion, but this would need some other mod per rack/site (yes, Equinix LD8 want individual positions "N+N", while Equinix LD6 expect a duplex port: "N") so even …

make a less confusing description for panel ports in LoA

---

resources/views/dashboard/index.foil.php

P2P and Peer to Peer Traffic tabs appear to do the same thing.

remove duplicate tab for P2P

---

data/travis-ci/known-good/ci-apiv4-b2-rs1-lan1-ipv6.conf
resources/views/api/v4/router/server/bird2/neighbor-template.foil.php
resources/views/api/v4/router/server/bird2/neighbors.foil.php

Move the "`interpret communities off`" option to the neighbor template, rather than repeating this config for every neighbor.

move rfc1997 communities config to neighbour template

---

resources/views/user-remember-token/list-row-override.foil.php

Replaced with hyphens for YYYY-MM-DD instead of YYYY:MM:DD
[BF] Weird time format for created_at column.
Fixes output like `2021:11:11 15:20:46` to `2021-11-11 15:20:46`

[BF] Weird time format for created_at column.

---

.env.example
config/mail.php

- Add new option MAIL_SENDMAIL_PATH to override sendmail path where the defaults are not appropriate
- sendmail -bs is the wrong option for this (crashes with error) should be sendmail -t 
This is useful for dev, or where you just need it to do the right thing, for example msmtp/msmtpd replaces the envelope sender
for non-existent users with something inappropriate.

[IM] allow override broken mail defaults

---

resources/views/customer/emails/welcome-email.blade.php

variable $vlanid is assigned incorrectly, because of it the netmask of IP addresses is empty
[NF] New feature summary - closes [inex|islandbridgenetworks]/IXP-Manager#x
- [ x] ensured all relevant template output is escaped to avoid XSS attached with `<?= $t->ee( $data ) ?>` or equivalent.
- [ x] ensured appropriate checks against user privilege / resources accessed
- [ x] API calls (particular for add/edit/delete/toggle) are not implemented with GET and use CSRF tokens to avoid CSRF attacks

fixing vlan id

---

resources/views/router/edit.foil.php

[BF] Fix help text when adding/editing router: Suggested format for handle should match format used in later examples.
Suggestion says to use format `purpose-proto-lan`, but handles used in examples use format `purpose-lan-proto`.

Router edit: Suggested format for `handle` matching examples

---

resources/views/customer/overview.foil.php

Link to reseller. Use more commonly displayed abbreviatedName.

Link to reseller. Use more commonly displayed abbreviatedName.

---

app/Models/Aggregators/SwitcherAggregator.php

See also #757
correctly group also by virtual interface id (was erroneously grouping interfaces together regardless of virtual interface id, so port in one VI rate_limit causes ports in other VI to also be listed a rate_limt.

[BF] group by virtualinterface id

---

resources/views/layer2-address/vlan-interface.foil.php

Fix typo so IP addresses display. Better description: "IP Addresses" as opposed to MAC Addresses (sometimes there are no IP addresses, so this will be blank)

[BF] IP Addresses not shown

---

resources/views/layer2-address/vlan-interface-cust.foil.php
resources/views/layer2-address/vlan-interface.foil.php

- Move the "+" button to the MAC address table heading.
- customer page: Don't hide the "+" button. If maximum MACs reached, grey out.
- customer page: Add message explaining what to do when maximum MACs reached.
- reduce table clutter on customer mac edit page.
Fixes https://github.com/inex/IXP-Manager/issues/799
We have implemented this to make it easier for members to understand how to manage their allowed MAC addresses.
It wasn't super obvious how to add MAC addresses, and sometimes the "+" button was hidden.
Before:
After:
- Plus button is in a more obvious place.
- Table clutter removed.
When maximum allowed MAC addresses reached:
- Plus button is in a more obvious place, but greyed out.  Hover message explains what it is/why it's disbled
- More obvious message. …

[IM] Make allowed MAC address editing more intuitive

---

app/Http/Controllers/Api/V4/MemberExportController.php

[BF] Fix a doc comment
The MemberExportController doc comment says it outputs "DNS ARPA records.
This looks like a copy-and-paste from another Controller that was never updated.

[BF] Fix a doc comment

---

app/Utils/Foil/Extensions/Bird.php
resources/views/services/lg/route.foil.php

[NF] Decode BGP well-known communities
This decodes BGP well-known communities in the looking glass.
Design decisions to review:
* ~~This follows the same patterns as the existing code. I'm not entirely sure why the existing code prepends the ":" when calling the matching function nor why it uses a `foreach` + `if` instead of an array index. But PHP is not my strong suit.~~
* I only included well-known communities that made it to a standard. There are ones allocated for Internet drafts. If you want to add those (or want me to), that's fine.
* I marked them all "info" except BLACKHOLE (because that likely indicates a DDoS is happening) and GRACEFUL_SHUTDOWN (because someone is about to do maintenance), which I marked as "warning".
In addition to the above, I have …

[NF] Decode BGP well-known communities

---

app/Models/VirtualInterface.php

This fixes a couple typos in a comment.

Fix typos in a VirtualInterface comment

---

tools/runtime/dns-arpa/update-dns-from-ixp-manager.sh

With (at least GNU) sed, you cannot have a space between the -i and the SUFFIX.
An alternative would be `--in-place=.bup`, but `--in-place` might be a GNUism, and I'm not sure if that's acceptable.

[BF] update-dns-from-ixp-manager: Fix sed -i.bup

---

app/Models/SwitchPort.php

[BF] mismatch between snmp polling attributes and db column names
$SwitchPort::SNMP_MAP and $SwitchPort::OSS_SNMP_MAU_MAP were incorrectly capitalised.
Some mau* parameters pulled from snmp were not correctly cast to tinyint {0,1} before committing to DB.

fix capitalisation for snmp polling

---

resources/views/database/views.foil.sql

[BF] Fixes the update:reset-mysql-views command
[this migration](https://github.com/inex/IXP-Manager/blob/master/database/migrations/2021_06_11_141137_update_db_doctrine2eloquent.php) breaks the views reset due to [this view reference](https://github.com/inex/IXP-Manager/blob/master/resources/views/database/views.foil.sql#L90).

Fix  update:reset-mysql-views artisan command

---

resources/views/customer/overview-tabs/ports/port.foil.php

Move aggregate graph so it's **_after_** the individual port graphs.
This is to make it more consistent
- **For non-LAG ports**: the graph related to the port always appears to the right of the physical port.
- **For LAG ports**: The LAG aggregate graph was appearing first, which shuffles down the physical port graphs making it harder to read which graph belongs to which physical port.
i.e., The graphs are aligned with the associated physical port, except **_sometimes_** they aren't.
**Mistakes have occurred because of this,** for example:
- Reading the wrong graph for a port.
- Looking for the port which traffic has dropped off, moving eyes left and then changing or unplugging the wrong crossconnect. 
**Before**: Here you can see I accidentally clicked the crossconnect for the port …

[IM] move aggregate graph after port graphs for more consistent alignment

---

app/Http/Controllers/Interfaces/PhysicalInterfaceController.php
resources/views/interfaces/common/js/interface-functions.foil.php

This PR fixes a bug/limitation which meant it was not possible to update physical interfaces of type "Reseller" (reseller uplink ports) without first having to change them back to "Peering" via Switches -> Switch Ports -> (Edit), then make the changes, then set it back to type "Reseller" in Switches -> Switch Ports -> (Edit).
It will also set a new port being added to a VirtualInterface to "Reseller" if existing port in VI is already set to "Reseller".

[BF/IM] Allow reseller uplink ports to be updated

---

resources/views/customer/list.foil.php

Small tweak in customer/member list. This column indicates a **Resold** customer, not a Reseller. (Despite the name of the field.)

[IM] Change column heading "reseller" to "resold"

---

resources/views/auth/forgot-password.foil.php
resources/views/auth/forgot-username.foil.php
resources/views/auth/login.foil.php
resources/views/auth/reset-password.foil.php

Configures a maximum size for the logo on the login page (and other pages) as svg logos are growing infinite in size
BEFORE:
AFTER:

landingpage: fix svg logos are too big

---

config/ixp_fe_settings.php

[BF] Typos, capitalization, language small fixes - fixes inex/IXP-Manager#938
Fix several typos in settings help text. Use the correct capitalization. 
(none checked above since only help text string values are changed)

[BF] Fix typos and other small language fixes in settings help
