inex/IXP-Manager

- application/configs/application.ini.dist
- application/controllers/CustomerController.php
- application/controllers/VlanInterfaceController.php
- application/views/customer/detail.phtml
- application/views/customer/overview-tabs/overview.phtml
- application/views/customer/overview-tabs/ports/port.phtml
- application/views/virtual-interface/forms/add-wizard.phtml
- application/views/vlan-interface/forms/vlan-interface.phtml
- library/IXP/Controller/Action.php
- library/IXP/Controller/CliAction.php
- library/IXP/Controller/Trait/Common.php
This "Works For Me" [TM] but I have barely touched any PHP since many years ago, so I wouldn't be surprised if I've missed a small edge-case somewhere...
> Add config-var to make as112 optional in UI (Fixes #217)

- Vagrantfile
hello barry
2nd try. hopefully better this time. :)
> support for vagrant-vmware_fusion provider #2

- application/views/customer/overview-tabs/details.phtml
> Revert "Fix exception when BillingFrequency or InvoiceMethod is empty"

- application/views/_skins/inex/statistics-cli/mrtg/trunks.cfg
> Added 80G MRTG Trunks

- public/css/ixp-manager.css
- resources/views/layouts/menus/superuser.foil.php
Top nav bar CSS issue on smaller screen widths
[BF] - Top nav bar CSS issue on smaller screen widths - fixes inex/IXP-Manager#378
> Top nav bar CSS issue on smaller screen widths

- resources/skins/inex/content/0/support.foil.php
Bad link on support page public-content/support
> [BF] - bad link on support page public-content/support

- resources/skins/inex/patch-panel-port/loa.foil.php
Fixed spelling: /correspondance/correspondence
> Fixed spelling: /correspondance/correspondence

- resources/views/dashboard/dashboard-tabs/details.foil.php
[BF] small typo correction: example.com8
> Small typo fixes

- app/Http/Controllers/Api/V4/Customer/Note/CustomerNotesController.php
- app/Http/Controllers/Customer/CustomerNotesController.php
- app/Listeners/Customer/Note/EmailOnChange.php
> [BF] - Customer Notes spam

- resources/views/services/lg/bgp-summary.foil.php
Reverts inex/IXP-Manager#547 as it breaks sorting in other columns.
> Revert "RS Looking Glass sort order - fixes inex/IXP-Manager#544"

- app/Http/Controllers/Interfaces/Common.php
- app/Http/Controllers/Interfaces/VirtualInterfaceController.php
- resources/views/interfaces/virtual/add/vi-details.foil.php
- tests/Browser/VirtualInterfaceControllerTest.php
> [IM] - Virtual Interface Name: spaces at the end of the string will b…e trim - fixes inex/IXP-Manager#513

- app/Http/Controllers/PatchPanel/PatchPanelPortController.php
- app/Http/Requests/StorePatchPanelPort.php
- database/xml/Entities.PatchPanelPort.dcm.xml
- database/xml/Entities.PatchPanelPortHistory.dcm.xml
> [BF] - 500 server error changing patch panel port - fixes inex/IXP-Manager#545

- app/Http/Controllers/Interfaces/CoreBundleController.php
- database/Repositories/CoreBundle.php
- database/Repositories/Customer.php
- resources/views/customer/overview.foil.php
> Fix issue delete customer

- app/Http/Controllers/Services/LookingGlass.php
- database/Repositories/Router.php
- resources/views/services/lg/index.foil.php
- resources/views/services/lg/layout.foil.php
- resources/views/services/lg/router-tab.foil.php
Add routers tabs Looking Glass
> Update looking glass fe

- app/Http/Controllers/AdminController.php
- app/Http/Controllers/Switches/SwitchController.php
- database/Repositories/PhysicalInterface.php
- database/Repositories/Switcher.php
- resources/views/admin/dashboard.foil.php
- resources/views/switches/configuration.foil.php
> Nf dashboard

- resources/views/layouts/menus/associate.foil.php
- resources/views/layouts/menus/custadmin.foil.php
- resources/views/layouts/menus/custuser.foil.php
- resources/views/layouts/menus/superuser.foil.php
- resources/views/profile/edit.foil.php
- tests/Browser/User2FAControllerTest.php
- tests/DuskTestCase.php
> 2fa dusk test

- app/Http/Controllers/Switches/SwitchPortController.php
- database/Repositories/SwitchPort.php
- resources/views/switch-port/page-header-preamble.foil.php
- resources/views/switches/list-row-menu.foil.php
- resources/views/switches/port-report.foil.php
*PR template - remove this line and edit below*
[NF] New feature summary - closes [inex|islandbridgenetworks]/IXP-Manager#x
> Fix issue switch port

- database/Repositories/IPv4Address.php
- database/Repositories/IPv6Address.php
- resources/views/ip-address/list.foil.php
> [Bf] - fix IP sorting - fixes inex/IXP-Manager#21

- tools/installers/README.md
Fixed filename for bash execution. :)
> Fixed execution filename

- resources/views/services/grapher/email/traffic-deltas.foil.php
Typo fix: "is this member's traffic"
> typo fix: is/in

- resources/skins/example/content/members/3/json-example.foil.php
This was falling over with a 500 error undefined function getId() - replaced with $c->id.
> [BF] replace getId() with $c->id (fixes 500 error)

- app/Tasks/Irrdb/UpdateAsnDb.php
[BF] Make ASN & prefix messages consistent
When a given customer is not a RS client, show the customer name in irrdb:update-asn-db, as irrdb:update-prefix-db already did.
> [BF] Make ASN & prefix messages consistent

- routes/apiv4.php
*PR template - remove this line and edit below*
[NF] New feature summary - closes [inex|islandbridgenetworks]/IXP-Manager#x
> Remove unintended line
